//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrenDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public Tovar()
        {
            this.Orders_Tovar = new HashSet<Orders_Tovar>();
        }
    
        public int T_Id { get; set; }
        public string T_Name { get; set; }
        public string T_Description { get; set; }
        public string T_Manufacturer { get; set; }
        public int T_Price { get; set; }
        public Nullable<int> T_Discount { get; set; }
        public Nullable<int> T_Count { get; set; }
        public string T_Image { get; set; }
    
        public virtual ICollection<Orders_Tovar> Orders_Tovar { get; set; }
    }
    public partial class Tovar
    {
        Entities entities = new Entities();
        public int totalPrice
        {
            get
            {
                if (this.T_Discount > 0)
                {
                    int discount = (Convert.ToInt32(this.T_Price * this.T_Discount) / 100);
                    return this.T_Price - discount;
                }
                else
                {
                    return this.T_Price;
                }
            }
        }
    }
    public partial class PickPoint
    {
        public override string ToString()
        {
            return P_Adress;
        }
    }
}
